# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-06 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=100)),
                ('poll_name', models.CharField(max_length=100)),
                ('vote', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
